files:
  _posts/2026-05-27-on-observing-oneself.md: https://thefaintsignal.substack.com/p/on-observing-oneself
  _posts/2026-06-11-el-problema-de-la-senal-democracia.md: https://thefaintsignal.substack.com/p/el-problema-de-la-senal-democracia
  _posts/2026-06-21-has-communism-ever-actually-failed.md: https://thefaintsignal.substack.com/p/has-communism-ever-actually-failed
  _posts/2026-07-05-no-time-for-feelings.md: https://thefaintsignal.substack.com/p/no-time-for-feelings
